server:
  port: 2011
  tomcat:
    uri-encoding: UTF-8
spring:
#--------------------------charset--------------------------
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
#    url: jdbc:mysql://localhost:3306/graduation?characterEncoding=UTf-8&amp;useSSL=false
    url: jdbc:mysql://localhost:3306/graduation?characterEncoding=UTF-8&amp;useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
mybatis:
  typeAliasesPackage: cn.xiaozi5.graduation.pojo
  
logging:
  level:
    org.apache.ibatis: debug
#logging:
#  config: classpath:cn/xiaozi5/graduation/conf/logconf.xml
#log:
#  dir: /logs/
#projectname: graduation