server:
  port: 2011
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/graduation?characterEncoding=UTf-8&amp;useSSL=false
    url: jdbc:mysql://localhost:3306/graduation?characterEncoding=UTf-8&amp;useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
logging:
  config: classpath:cn/xiaozi5/graduation/conf/logconf.xml
log:
  dir: /logs/
projectname: graduation